spring:
  application:
    name: compras-service
  jackson:
    serialization:
      fail-on-empty-beans: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  rabbitmq:
    port: 5777
    host: localhost
    username: guest
    password: guest

server:
  port: 8085
  instance: PRIMEIRO

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    hostname: localhost
    port: 8081
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

mail:
  smtp:
    auth: true
    starttls:
      enable: true
    host: smtp.gmail.com
    port: 587
  myAccountEmail: ifeiranotificacao@gmail.com
  password: 123456Aa@

security:
  oauth2:
    service-id: auth-service
    client:
      resource-id: 368b0ae8-09be-11eb-adc1-0242ac120002
    resource:
      userInfoUri: http://${security.oauth2.service-id}/user/userinfo

api-pagamento:
  pag-id: sandbox.boletobancario.com
  oauth:
    id: "XMkSp17rT9J8bbN5"
    secret: ">V}EsQg+48Xn}i[<0pJqBw9gwOy;XbCH"
    grant_type: "client_credentials"
    oauth_url: https://${api-pagamento.pag-id}/authorization-server/oauth/token
  url: https://${api-pagamento.pag-id}/api-integration/charges
  url_tokenizacao: https://${api-pagamento.pag-id}/api-integration/credit-cards/tokenization
  private_token: CA3499B3127E237FB9905E458EDC9401E1D299CF0813FDC5525B363E5E96D262
  public_token: B2D0B12E73A21E783D130F46AD79A05EFA4E3460D6D8ECCFB805C61CB02D1741
  api_version: 2

#
#ribbon:
#  IsSecure: true

mq:
  -
    queue-name: pagamentos_pendentes
    exchange-name: pagamentos_pendentes_exchange
    routing-key: pagamentos_pendentes_key

bd:
  url: jdbc:mysql://localhost:3306/IFEIRA?useTimezone=true&serverTimezone=UTC
  username: root
  password: 1234
  driverClassName: com.mysql.cj.jdbc.Driver