spring:
  application:
    name: compras-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=fatectcc
    username: SA
    password: fatec2020@A
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    dialect: org.hibernate.dialect.SQLServer2012Dialect
    format_sql: true
    hibernate:
      ddl-auto: 'update'

server:
  port: 8085
  instance: PRIMEIRO


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 30
    prefer-ip-address: true
    hostname: localhost
    port: 8081
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000