spring:
  application:
    name: compras-service

server:
  port: 8087
  instance: terceiro

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 30
    prefer-ip-address: true
    hostname: localhost
    port: 8081
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

authserver:
  hostname: http://auth-server:9092

security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user/userinfo
    client:
      resource-id: 368b0ae8-09be-11eb-adc1-0242ac120002