spring:
  application:
    name: entregas-service
  jackson:
    serialization:
      fail-on-empty-beans: false
  rabbitmq:
    port: 5777
    host: RABBITMQ
    username: guest
    password: guest

server:
  port: 8105
  instance: PRIMEIRO

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    hostname: discovery
    port: 8081
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
  oauth2:
    service-id: auth-service
    client:
      resource-id: 368b0ae8-09be-11eb-adc1-0242ac120002
    resource:
      userInfoUri: http://${security.oauth2.service-id}/user/userinfo

mail:
  smtp:
    auth: true
    starttls:
      enable: true
    host: smtp.gmail.com
    port: 587
  myAccountEmail: ifeiranotificacao@gmail.com
  password: 123456Aa@

bd:
  url: jdbc:mysql://mysqltcc:3306/IFEIRA?useTimezone=true&serverTimezone=UTC
  username: root
  password: 1234
  driverClassName: com.mysql.cj.jdbc.Driver

mq:
  -
    queue-name: pagamentos_concluidos
    exchange-name: pagamentos_concluidos_exchange
    routing-key: pagamentos_concluidos

