CREATE TABLE PRODUTO (
	COD					VARCHAR(20) 	NOT NULL,
	NOME 				VARCHAR(200)	NOT NULL,
	DESCRICAO			VARCHAR(200),
	TIPO_PRODUTO		VARCHAR(20)		NOT NULL,
	IMAGE_URL			VARCHAR(500)	NOT NULL
	PRIMARY KEY(COD)
)

CREATE TABLE FEIRA (
	ID 					INT 		 	NOT NULL AUTO_INCREMENT,
	ID_ENDERECO			INT 			NOT NULL,
	NOME 				VARCHAR(200)	NOT NULL,
	TELEFONE_CONTATO	VARCHAR(15),
	CONTEXTO			VARCHAR(20)		NOT NULL,
	LATITUDE			VARCHAR(50)		NOT NULL,
	LONGITUDE			VARCHAR(50)		NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID)
)

CREATE TABLE ENDERECO (
	ID 					INT 		 	NOT NULL AUTO_INCREMENT,
	NUMERO 				VARCHAR(20)		NOT NULL,
	CEP					VARCHAR(20)		NOT NULL,
	COMPLEMENTO			VARCHAR(200)	NOT NULL,
	BAIRRO				VARCHAR(200)	NOT NULL,
	CIDADE				VARCHAR(200)	NOT NULL,
	UF					VARCHAR(2)		NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE PRODUTO_FEIRA (
	COD_PRODUTO 	VARCHAR(20)  	NOT NULL,
	ID_FEIRA 		INT 		 	NOT NULL,
	PRECO			DECIMAL(7,2) 	NOT NULL,
	ATIVO			BOOLEAN 		NOT NULL,
	UNIDADE_MEDIDA 	VARCHAR(50) 	NOT NULL,
	PRIMARY KEY(COD_PRODUTO, ID_FEIRA),
	FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD),
	FOREIGN KEY(ID_FEIRA) REFERENCES FEIRA(ID)
)