USE IFEIRA

CREATE TABLE ENDERECO (
	ID 					INT 		 	NOT NULL AUTO_INCREMENT,
	NUMERO 				VARCHAR(20)		NOT NULL,
	CEP					VARCHAR(20)		NOT NULL,
	COMPLEMENTO			VARCHAR(200)	NOT NULL,
	BAIRRO				VARCHAR(200)	NOT NULL,
	CIDADE				VARCHAR(200)	NOT NULL,
	UF					VARCHAR(2)		NOT NULL,
	LOGRADOURO 			VARCHAR(200)	NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE PESSOA (
	CPF 			VARCHAR(11)		NOT NULL,
	NOME 			VARCHAR(200)	NOT NULL,
	SOBRENOME 		VARCHAR(200)	NOT NULL,
	EMAIL			VARCHAR(200)	NOT NULL UNIQUE,
	DATA_NASC		DATE			NOT NULL,
	SEXO			VARCHAR(15)		NOT NULL,
	ID_ENDERECO 	INT				NOT NULL,
	TELEFONE		VARCHAR(15)		NOT NULL,
	ROLE			VARCHAR(20)		NOT NULL,
	SITUACAO 		VARCHAR(200) 	NOT NULL,
	SENHA			VARCHAR(200)	NOT NULL,
	PRIMARY KEY(CPF),
	FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID)
);

CREATE TABLE PRODUTO (
	COD					VARCHAR(20) 	NOT NULL,
	NOME 				VARCHAR(200)	NOT NULL,
	DESCRICAO			VARCHAR(200),
	TIPO_PRODUTO		VARCHAR(20)		NOT NULL,
	IMAGE_URL			VARCHAR(500)	NOT NULL,
	PRIMARY KEY(COD)
);

CREATE TABLE FEIRA (
	CONTEXTO			VARCHAR(20)		PRIMARY KEY,
	ID_ENDERECO			INT 			NOT NULL,
	NOME 				VARCHAR(200)	NOT NULL,
	TELEFONE_CONTATO	VARCHAR(15),
	LATITUDE			VARCHAR(50)		NOT NULL,
	LONGITUDE			VARCHAR(50)		NOT NULL,
	DIA_ENTREGA			INT				NOT NULL,
	FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID)
);

-- 1 - DOMINGO, 2 - SEGUNDA, 3 - TERÇA, 4 - QUARTA, 5 - QUINTA, 6 - SEXTA, 7 - SABADO

CREATE TABLE PRODUTO_FEIRA (
	COD_PRODUTO 	VARCHAR(20)  	NOT NULL,
	CONTEXTO		VARCHAR(20)		NOT NULL,
	PRECO			DECIMAL(7,2) 	NOT NULL,
	ATIVO			BOOLEAN 		NOT NULL,
	UNIDADE_MEDIDA 	VARCHAR(50) 	NOT NULL,
	PRIMARY KEY(COD_PRODUTO, CONTEXTO),
	FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD),
	FOREIGN KEY(CONTEXTO) REFERENCES FEIRA(CONTEXTO)
);

CREATE TABLE CUPOM(
	NOME VARCHAR(200) NOT NULL,
	PORCENTAGEM DECIMAL(7,2) NOT NULL,
	ATIVO BOOLEAN NOT NULL,
	PRIMARY KEY(NOME)
);

CREATE TABLE PEDIDO (
	NUMERO			BIGINT			NOT NULL AUTO_INCREMENT,
	DATA_PEDIDO		DATE 			NOT NULL,
	STATUS_PEDIDO	VARCHAR(50)		NOT NULL,
	DATA_ENTREGA	DATE,
	CUPOM			VARCHAR(200)	NOT NULL,
	CPF_PESSOA		VARCHAR(11)		NOT NULL,
	COBRANCA		VARCHAR(200)		NOT NULL,
	VALOR_TOTAL		DECIMAL(7,2)	NOT NULL,
	VALOR_ORIGINAL  DECIMAL(7,2),
	PRIMARY KEY(NUMERO),
	FOREIGN KEY (CPF_PESSOA)	REFERENCES PESSOA(CPF)
);

CREATE TABLE PAGAMENTO (
	ID					BIGINT			NOT NULL AUTO_INCREMENT,
	NUMERO_PEDIDO		BIGINT			NOT NULL,
	NOME_CARTAO         VARCHAR(100),
	NUMERO_CARTAO		BLOB,
	VALIDADE_CARTAO		BLOB,
	CVV					BLOB,
	DATA_PAGAMENTO		DATE			NOT NULL,
	STATUS_PAGAMENTO    VARCHAR(50)     NOT NULL,
	SALVA_DADOS_PAG     BOOLEAN         NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDO(NUMERO)
);

CREATE TABLE CARRINHO (
	NUMERO_PEDIDO	BIGINT			NOT NULL,
	COD_PRODUTO 	VARCHAR(20)  	NOT NULL,
	CONTEXTO		VARCHAR(20)		NOT NULL,
	QUANTIDADE		INT				NOT NULL,
	PRIMARY KEY CARRINHO (COD_PRODUTO, CONTEXTO, NUMERO_PEDIDO),
	FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD),
	FOREIGN KEY(CONTEXTO) REFERENCES FEIRA(CONTEXTO),
	FOREIGN KEY(NUMERO_PEDIDO) REFERENCES PEDIDO(NUMERO)
);

CREATE TABLE ENTREGADOR_FEIRA (
	CONTEXTO			VARCHAR(20) NOT NULL,
	CPF_ENTREGADOR		VARCHAR(11) NOT NULL,
	PRIMARY KEY (CONTEXTO, CPF_ENTREGADOR),
	FOREIGN KEY (CONTEXTO) REFERENCES FEIRA (CONTEXTO),
	FOREIGN KEY (CPF_ENTREGADOR) REFERENCES PESSOA (CPF)
);

CREATE TABLE SALDO_ADMIN (
	ID_PAGAMENTO	BIGINT,
	VALOR_TOTAL		DECIMAL(7,2)
);

CREATE TABLE SALDO_FEIRANTE (
	NUMERO_PEDIDO	BIGINT,
	ID_FEIRA		VARCHAR(20),
	VALOR_TOTAL		DECIMAL(7,2)
);

CREATE TABLE SALDO_ENTREGADOR (
	NUMERO_PEDIDO	BIGINT,
	CPF_ENTREGADOR	VARCHAR(11),
	VALOR_TOTAL		DECIMAL(7,2)
);

CREATE TABLE ENTREGA (
	ID					BIGINT		NOT NULL AUTO_INCREMENT,
	CPF_ENTREGADOR		VARCHAR(11) NOT NULL,
	NUMERO_PEDIDO		BIGINT		NOT NULL,
	DATA_REALIZACAO		DATE,
	STATUS_ENTREGA		VARCHAR(20)	NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CPF_ENTREGADOR) REFERENCES PESSOA(CPF),
	FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDO(NUMERO)
);

CREATE INDEX IDX_SA_ADM ON SALDO_ADMIN (ID_PAGAMENTO);

CREATE INDEX IDX_SF ON SALDO_FEIRANTE (NUMERO_PEDIDO, ID_FEIRA);

CREATE INDEX IDX_SE ON SALDO_ENTREGADOR (NUMERO_PEDIDO, CPF_ENTREGADOR);