INSERT INTO PRODUTO VALUES('FRUT1', 'Abacate Mexicano', 'Uma delícia', 'FRUTA', '');
INSERT INTO PRODUTO VALUES('FRUT2', 'Abacaxi Vitória', 'Uma delícia', 'FRUTA', '');
INSERT INTO PRODUTO VALUES('FRUT3', 'Mamão Papaya', 'Uma delícia', 'FRUTA', '');
INSERT INTO PRODUTO VALUES('FRUT4', 'Laranja Pera', 'Uma delícia', 'FRUTA', '');
INSERT INTO PRODUTO VALUES('FRUT5', 'Maçã Argentina', 'Uma delícia', 'FRUTA', '');
INSERT INTO PRODUTO VALUES('FRUT6', 'Laranja Lima', 'Uma delícia', 'FRUTA', '');
INSERT INTO PRODUTO VALUES('FRUT7', 'Carambola', 'Uma delícia', 'FRUTA', '');
INSERT INTO PRODUTO VALUES('FRUT8', 'Melancia Forrageira', 'Uma delícia', 'FRUTA', '');
INSERT INTO PRODUTO VALUES('VER1', 'Alface Crespo', 'Uma delícia', 'VERDURA', '');
INSERT INTO PRODUTO VALUES('VER2', 'Alface Lisa', 'Uma delícia', 'VERDURA', '');
INSERT INTO PRODUTO VALUES('VER3', 'Couve Galega', 'Uma delícia', 'VERDURA', '');
INSERT INTO PRODUTO VALUES('VER4', 'Agrião', 'Uma delícia', 'VERDURA', '');
INSERT INTO PRODUTO VALUES('VER5', 'Repolho', 'Uma delícia', 'VERDURA', '');
INSERT INTO PRODUTO VALUES('VER6', 'Repolho Roxo', 'Uma delícia', 'VERDURA', '');
INSERT INTO PRODUTO VALUES('VER7', 'Coentro', 'Uma delícia', 'VERDURA', '');
INSERT INTO PRODUTO VALUES('VER8', 'Rúcula', 'Uma delícia', 'VERDURA', '');
INSERT INTO PRODUTO VALUES('LEG1', 'Abóbora', 'Uma delícia', 'LEGUMES', '');
INSERT INTO PRODUTO VALUES('LEG2', 'Abóbora Japonesa', 'Uma delícia', 'LEGUMES', '');
INSERT INTO PRODUTO VALUES('LEG3', 'Abobrinha', 'Uma delícia', 'LEGUMES', '');
INSERT INTO PRODUTO VALUES('LEG4', 'Berinjela', 'Uma delícia', 'LEGUMES', '');
INSERT INTO PRODUTO VALUES('LEG5', 'Pimentão Vermelho', 'Uma delícia', 'LEGUMES', '');
INSERT INTO PRODUTO VALUES('LEG6', 'Quiabo', 'Uma delícia', 'LEGUMES', '');
INSERT INTO PRODUTO VALUES('LEG7', 'Tomate Caqui', 'Uma delícia', 'LEGUMES', '');
INSERT INTO PRODUTO VALUES('LEG8', 'Mandioquinha', 'Uma delícia', 'LEGUMES', '');

INSERT INTO ENDERECO(NUMERO, CEP, COMPLEMENTO, BAIRRO, CIDADE, UF, LOGRADOURO) VALUES('442', '44002080', 'DO LADO DA CASA BRANCA', 'Rua 13 de Novembro', 'Feira de Santana', 'BA', 'Rua da Feira de Santana');

INSERT INTO FEIRA(ID_ENDERECO, NOME, TELEFONE_CONTATO, CONTEXTO, LATITUDE, LONGITUDE, DIA_ENTREGA) VALUES(1, 'Feira da Feira de Santana', '73999988888', 'ffsantana', '-12.2626582', '-38.9577475', 6);

INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('FRUT1', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('FRUT2', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('FRUT3', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('FRUT4', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('FRUT5', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('FRUT6', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('FRUT7', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('FRUT8', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('VER1', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('VER2', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('VER3', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('VER4', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('VER5', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('VER6', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('VER7', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('VER8', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('LEG1', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('LEG2', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('LEG3', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('LEG4', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('LEG5', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('LEG6', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('LEG7', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');
INSERT INTO PRODUTO_FEIRA (COD_PRODUTO,  CONTEXTO, PRECO, ATIVO, UNIDADE_MEDIDA) VALUES('LEG8', 'ffsantana', round(rand() * 7 + 0.01, 2), true, 'Kilo');


INSERT INTO PESSOA
(CPF, NOME, SOBRENOME, EMAIL, DATA_NASC, SEXO, ID_ENDERECO, TELEFONE, `ROLE`, SENHA, SITUACAO)
VALUES('41846827825', 'Bruno', 'Cardoso', 'brunofc11@gmail.com', '1994-03-28', 'MASCULINO', 1, '123', 0, '$2a$10$TXgWkEboM/kfUZoN.ePX4uoCdR0OCKj8bSqo0ZQ.TKEyplOgvcy9m', 'HABILITADO');

INSERT INTO CUPOM VALUES ('FEIRA10', 10.0, true);

--INSERT INTO PESSOA
--(CPF, NOME, SOBRENOME, EMAIL, DATA_NASC, SEXO, ID_ENDERECO, TELEFONE, `ROLE`, SENHA, SITUACAO)
--VALUES('28701508067', 'Everson', 'Bacelli', 'everson.bacelli@gmail.com', '1994-03-28', 'MASCULINO', 1, '123', 2, '$2a$10$/XFpGPkMxz6VEfuqqJhVNu9Cf7bbofcWatS2I7tHIZjM8s3icyhE.', 'HABILITADO');

--insert into ENTREGADOR_FEIRA values ('ffsantana', '28701508067')