spring:
  application:
    name: pagamentos-service
  jackson:
    serialization:
      fail-on-empty-beans: false
  rabbitmq:
    port: 5777
    host: localhost
    username: guest
    password: guest

server:
  port: 8095
  instance: PRIMEIRO


mq:
  -
    queue-name: pagamentos_pendentes
    exchange-name: pagamentos_pendentes_exchange
    routing-key: pagamentos_pendentes_key
    timeout: 2
  -
    queue-name: pagamentos_concluidos
    exchange-name: pagamentos_concluidos_exchange
    routing-key: pagamentos_concluidos
    timeout: 2

api-pagamento:
  oauth:
    id: "XMkSp17rT9J8bbN5"
    secret: ">V}EsQg+48Xn}i[<0pJqBw9gwOy;XbCH"
    grant_type: "client_credentials"
    oauth_url: https://sandbox.boletobancario.com/authorization-server/oauth/token
  url: https://sandbox.boletobancario.com/api-integration/payments
  private_token: CA3499B3127E237FB9905E458EDC9401E1D299CF0813FDC5525B363E5E96D262
  public_token: B2D0B12E73A21E783D130F46AD79A05EFA4E3460D6D8ECCFB805C61CB02D1741
  api_version: 2

mail:
  smtp:
    auth: true
    starttls:
      enable: true
    host: smtp.gmail.com
    port: 587
  myAccountEmail: ifeiranotificacao@gmail.com
  password: 123456Aa@

bd:
  url: jdbc:mysql://localhost:3306/IFEIRA?useTimezone=true&serverTimezone=UTC
  username: root
  password: 1234
  driverClassName: com.mysql.cj.jdbc.Driver