spring:
  application:
    name: discovery-server
server:
  port: 8081

logging:
  level:
    com:
      netflix:
        discovery: INFO
        eureka: INFO

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
    hostname: 10.2.0.7
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 1000
    responseCacheUpdateInvervalMs: 5
    #    renewalPercentThreshold: 0
    #    renewalPercentThreshold: 0.85
    #    renewal-percent-threshold: 1
    #    responseCacheUpdateInvervalMs: 200
#    enableSelfPreservation: true
#    enable-self-preservation: false
#    evictionIntervalTimerInMs: 100

