server:
  port: 9092

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/fatectcc?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    dialect: org.hibernate.dialect.MySQL8Dialect
    format_sql: true
    hibernate:
      ddl-auto: 'update'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    hostname: localhost
    port: 8081
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

security:
  oauth2:
    client:
      client-id: 2befa526-09be-11eb-adc1-0242ac120002
      client-secret: 33216d66-09be-11eb-adc1-0242ac120002
      resource-id: 368b0ae8-09be-11eb-adc1-0242ac120002
      acess-token-validity: 3600
      scopes: read,write
      authorized-grant-types: password,refresh_token,client_credentials
